### ISSUE TITLE
Megalinter 8.6.0 Sanitize - gitleaks external dependency

### ISSUE THREAD

**Issue by raphaelzoellner** [oxsecurity/megalinter#5283]
I've noticed running Megalinter 8.6.0 enabling only REPOSITORY_GITLEAKS or TRIVY_SBOM froze execution (>1h) during a one shot run.

Using the same configuration in Megalinter 8.5.0 did not freeze execution.

Running Megalinter 8.6.0 with debug logs enabled I observed logs of the form as the last log entries before the freeze happened:

```
+----MATCHING LINTERS-----+----------+----------------+------------+
| Descriptor | Linter     | Criteria | Matching files | Format/Fix |
+------------+------------+----------+----------------+------------+
| REPOSITORY | trivy-sbom |          | project        | no         |
+------------+------------+----------+----------------+------------+

[Pre][REPOSITORY] No commands declared in user configuration
[trivy-sbom] command: ['trivy', 'fs', '--format', 'cyclonedx', '.']
[trivy-sbom] CWD: /code
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /gitleaks/gitleaks/refs/heads/master/config/gitleaks.toml HTTP/1.1" 200 20522
Invalid regex pattern after fix: (?i)[\w.-]{0,50}?(?:gocardless)(?:[ \t\w.-]{0,20})[\s'"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'"\s=]{0,5}(live_(?i)[a-z0-9\-_=]{40})(?:[\x60'"\s;]|\\[nr]|$). Error: global flags not at the start of the expression at position 114
Invalid regex pattern after fix: (?i)\b(pscale_pw_(?i)[\w=\.-]{32,64})(?:[\x60'"\s;]|\\[nr]|$). Error: global flags not at the start of the expression at position 17
```

It seems like https://github.com/oxsecurity/megalinter/pull/5266 introduced a dependency to a [default gitleaks configuration](https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml) on the master branch.

https://github.com/oxsecurity/megalinter/blob/v8.6.0/megalinter/logger.py#L165

Since the master branch is a moving target, errors in the gitleaks configuration might be the reason for the freeze.

Is there any configuration option for a Megalinter user to either provide their own gitleaks configuration for the sanitize or to disable it, such that no connection to github is necessary?

**Comment by wesley-dean** [comment]
In the [documentation](https://megalinter.io/latest/descriptors/repository_gitleaks/), `REPOSITORY_GITLEAKS_CONFIG_FILE` is used to specify the configuration file.  If not specified, a [default](https://github.com/oxsecurity/megalinter/tree/main/TEMPLATES/.gitleaks.toml) is used.

**Comment by markusschaefer** [comment]
The Executiontime raises with 8.6.0 up to more than 10 min. With older versions the one-shot run needs less than 3 minutes. The container runs without access to GitHub into multiple timeouts before using the local config file.

**Comment by raphaelzoellner** [comment]
I accidently closed this, could you reopen the issue?

**Comment by nvuillam** [comment]
@raphaelzoellner working on a way to exclude the too heavy regexes :)

**Comment by raphaelzoellner** [comment]
@nvuillam,

I've retried and it seems the performance issue was fixed by a new gitleaks commit on master: 
https://github.com/gitleaks/gitleaks/pull/1848

The changes from
https://github.com/oxsecurity/megalinter/pull/5308
seem to have no impact on the performance for the given data.
I've reproduced the behavior by updating the fetch url to the previous gitleaks commit where the regexes had potential for catastrophic backtracking, the linting run requires >10mins (which is when I stopped it) whereas with the new gitleaks regexes (from the gitleaks master branch) it requires <2mins.
https://github.com/oxsecurity/megalinter/blob/v8.6.0/megalinter/logger.py#L165
`https://raw.githubusercontent.com/gitleaks/gitleaks/4451b455f3d6757985070ac244097acec4af74bb/config/gitleaks.toml`

But setting the environment variable `SKIP_LINTER_OUTPUT_SANITIZATION` does seem to skip the sanitazation as you mentioned resulting in <2mins for the run again.

I still think it would be advantageous for Megalinter to not depend on the gitleaks master branch (HTTPS Connection) by default, because of air-gapped scenarios where the linter might be run. I think this could be achieved by bundling the sanitazation regex patterns in the docker image, one could even think about giving the user the option to override the defaults. I think this might be worth another feature request, for now the regex performance issue can be handled by setting `SKIP_LINTER_OUTPUT_SANITIZATION`. Thanks a lot!

**Comment by martynvdijke** [comment]
Hey all,

I am also experiencing similar issues, we have an air gapped environment unable to reach github.com.
So, I would indeed second the amendment that megalinter is better of using an own packaged gitleaks.toml ruleset than loading one from the internet.
Even by setting the `SKIP_LINTER_OUTPUT_SANITIZATION= true` I still get issues that megalinter is trying to contact github for a gitleaks.toml and fails after a couple of minutes on timeouts leading to increased CI times.

```bash
Could not fetch Gitleaks config from URL. Error: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /gitleaks/gitleaks/refs/heads/master/config/gitleaks.toml
```

I am pretty sure it comes from the `fetch_gitleaks_regexes` function at https://github.com/oxsecurity/megalinter/blob/65e0bb20d81bdcd397bc54a0b5ebe1b9e3cd6f03/megalinter/logger.py#L163-L176.

Which is not being skipped by the `SKIP_LINTER_OUTPUT_SANITIZATION`  setting.

I am not sure what the best approach is either a setting to not download the gitleaks.toml from the internet or always using a packages version together with megalinter ?
Anyway open to help and discuss.

**Comment by nvuillam** [comment]
@martynvdijke sorry i thought i avoid to call gitleaks rules if the variable was set, i reopen the issue and i'll have a look

**Comment by nvuillam** [comment]
@martynvdijke 

the code is the following

![Image](https://github.com/user-attachments/assets/53d0048a-395d-41f1-98bc-d6648bae24e1)

You need to define SKIP_LINTER_OUTPUT_SANITIZATION directly in the step environment variable and not in the .mega-linter.yml (the config is not read yet when we call the logger the first time)

I'll also add a variable to force to use the local version of gitleaks.toml rules in case you are offline

**Comment by martynvdijke** [comment]
Hey @nvuillam you are 100% right.
Sorry I did not see it yesterday, I was setting the env var to `True` but it really needs to be `true`.
Thanks for investigating setting the env to `true` fixes it indeed and does not pull the gitleaks.toml from github.

**Comment by nvuillam** [comment]
@martynvdijke i'm glad the workaround finally works for you 😊
